// <auto-generated />
using System;
using BurgerRoyale.Auth.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BurgerRoyale.Auth.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BurgerRoyale.Auth.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserRole")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c39285ad-fd4d-49d7-a886-96bb62507212"),
                            Cpf = "00000000000",
                            CreatedAt = new DateTime(2024, 3, 8, 18, 28, 48, 875, DateTimeKind.Utc).AddTicks(3810),
                            Email = "admin@burgerroyale.com",
                            Name = "Admin",
                            PasswordHash = "$2a$11$C99.K9/gfTc0RqR8XYAiu.T3BG/GvWgOt2oggKkyivz9dGpZPwpEy",
                            UserRole = 0
                        },
                        new
                        {
                            Id = new Guid("392d716a-20af-48a7-b8ef-e443dd4d8134"),
                            Cpf = "11111111111",
                            CreatedAt = new DateTime(2024, 3, 8, 18, 28, 48, 875, DateTimeKind.Utc).AddTicks(4849),
                            Email = "customer@burgerroyale.com",
                            Name = "Customer",
                            PasswordHash = "$2a$11$mDJa/xLGCCAYzxhDpcmYve8NpaBqMeCMMfVbB9NpGqg/SpaRv3gJq",
                            UserRole = 1
                        },
                        new
                        {
                            Id = new Guid("c41144a9-7bc0-4444-a041-a1cdbba46d90"),
                            Cpf = "22222222222",
                            CreatedAt = new DateTime(2024, 3, 8, 18, 28, 48, 875, DateTimeKind.Utc).AddTicks(5246),
                            Email = "employee@burgerroyale.com",
                            Name = "Employee",
                            PasswordHash = "$2a$11$hIwenwL9SKoqgwWt0EOQgukwjCDP1tVuij0lMtHk9nGSwnIVbzbM2",
                            UserRole = 2
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
