name: BurgerRoyale Auth - Build and Test

on:
  workflow_call: 
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test
      run: dotnet test --no-build --verbosity normal

  sonar:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest    
    needs: build
    steps:
      - name: Setup SonarCloud
        shell: powershell
        run: | 
          dotnet tool install --global dotnet-sonarscanner

      - name: Analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        shell: powershell
        run: |
          dotnet sonarscanner begin /k:"BurgerRoyale.Auth" /o:"3soat-burger-royale" /d:sonar.token="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io"
          dotnet build
          dotnet test --collect "Code Coverage"
          dotnet sonarscanner end