name: BurgerRoyale.Auth

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main", "develop" ]

env:
  ECR_REPOSITORY: burgerroyaleauth
  LAMBDA_FUNCTION_NAME: burgerroyaleauth-lambda

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test
      run: dotnet test --no-build --verbosity normal

  publishImage:
    if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
    name: Publish Docker image
    runs-on: ubuntu-latest
    needs: build

    steps:    
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Docker Image
        run: docker build -t ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:latest .

      - name: Tag Docker Image
        run: docker tag ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:latest ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:$(date +%s)

      - name: Push Docker Image to ECR
        run: docker push ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY

      - name: Update lambda function code
        run: |
          aws lambda update-function-code --function-name $LAMBDA_FUNCTION_NAME --image-uri ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:latest

  updateLambda:
    if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
    name: Update lambda function
    runs-on: ubuntu-latest
    needs: publishImage

    steps:    
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Update lambda function code
        run: |
          aws lambda update-function-code --function-name $LAMBDA_FUNCTION_NAME --image-uri ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:latest
