name: BurgerRoyale Auth - Deploy Lambda

on:
  workflow_dispatch: 
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'README.md'
      - '.gitignore'
      - '.github/workflows/**'

env:
  ECR_REPOSITORY: burgerroyaleauth
  LAMBDA_FUNCTION_NAME: burgerroyaleauth-lambda

jobs:
  publishImage:
    name: Publish Docker image
    uses: FiapSoftwareArquitectureTechChallange/BurgerRoyale.Auth/.github/workflows/publish-image.yml@main
        
  updateLambda:
    name: Update lambda function
    runs-on: ubuntu-latest
    needs: publishImage

    steps:    
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Update lambda function code
        run: |
          aws lambda update-function-code --function-name $LAMBDA_FUNCTION_NAME --image-uri ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:latest
