name: BurgerRoyale Auth - Publish Image

on:
  workflow_dispatch:
  workflow_call: 

env:
  ECR_REPOSITORY: burgerroyaleauth
  LAMBDA_FUNCTION_NAME: burgerroyaleauth-lambda

jobs:
  build:
    name: Build and Test
    uses: FiapSoftwareArquitectureTechChallange/BurgerRoyale.Auth/.github/workflows/build-and-test.yml@main
    secrets: inherit

  publishImage:
    name: Publish Docker image
    runs-on: ubuntu-latest
    needs: build

    steps:    
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Docker Image
        run: docker build -t $ECR_REPOSITORY .

      - name: Tag Docker Image
        run: docker tag $ECR_REPOSITORY:latest ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:latest

      - name: Push Docker Image to ECR
        run: docker push ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:latest
